#!/bin/bash
## G.Smith-Vidaurre & D. Schmidt
## 04 September 2020
## Updated 08 Feb 2021

## Purpose: Use bowtie2 to index the monk parakeet genome FASTA file for mapping SE and PE reads. This script only needs to be run once. bowtie version 2.3.5.1 will be called by default (determined this by running module avail)

#SBATCH --job-name bowtie_index
#SBATCH --partition normal ## default
#SBATCH --nodes 1 ## default
#SBATCH --ntasks 1 ## default
#SBATCH --cpus-per-task 32 ## number of threads, default is 1, changes ntasks, I still find that confusing
#SBATCH --mem-per-cpu 800M # default is 500M
#SBATCH --time 2-01:00:00 ## Must be specified, the default for this partition is 7 days 1 hour max walltime (7-01:00:00)
#SBATCH --mail-user gsmithvi@nmsu.edu
#SBATCH --mail-type BEGIN ## will get an email when job starts
#SBATCH --mail-type END ## will get an email when job ends
#SBATCH --mail-type FAIL ## will get email when job fails
#SBATCH --get-user-env ## pass on environmental settings

module load bowtie2

path=/scratch/gsmithvi/Genome/GCA_013036005.1_ASM1303600v1
log_file=$path/bowtie2_index_genome.oe

bowtie2-build -f $path/GCA_013036005.1_ASM1303600v1_genomic.fna.gz GCA_013036005.1_ASM1303600v1 &> $log_file
