#!/bin/bash
## G.Smith-Vidaurre & D. Schmidt 
## 13 February 2021
## Updated 21 February 2021

## Purpose: Use the gstacks module of the Stacks 2.53 pipeline to genotype SE reads for genotyping accuracy comparison. NOTE: must be run from the relevant directory.

#SBATCH --job-name gstacks_PE_geno_accur
#SBATCH --partition normal ## default
#SBATCH --nodes 1 ## default
#SBATCH --ntasks 1 ## default
#SBATCH --cpus-per-task 32 ## number of threads, default is 1, changes ntasks, I still find that confusing
#SBATCH --mem-per-cpu 1000M # default is 500M
#SBATCH --time 4-01:00:00 ## Must be specified, the default for this partition is 7 days 1 hour max walltime (7-01:00:00)
#SBATCH --mail-user gsmithvi@nmsu.edu
#SBATCH --mail-type BEGIN ## will get an email when job starts
#SBATCH --mail-type END ## will get an email when job ends
#SBATCH --mail-type FAIL ## will get email when job fails
#SBATCH --get-user-env ## pass on environmental settings

module load stacks 

path=/scratch/gsmithvi/geno_accur/paired_end/
log_file=$path/gstacks.oe

gstacks -I PE_sorted_bam -M PE_popmap_gstacks_geno_accur.txt -O PE_gstacks --rm-pcr-duplicates


