#!/bin/bash
## G.Smith-Vidaurre
## 26 June 2020
## Updated 02 Aug 2020

## Purpose: Filter the paired-end libraries for PCR clones

#SBATCH --job-name PE_clones
#SBATCH --partition normal ## default
#SBATCH --nodes 1 ## default
#SBATCH --ntasks 1 ## default
#SBATCH --cpus-per-task 32 ## updated from 16 to 32, number of threads, default is 1, changes ntasks, I still find that confusing
#SBATCH --mem-per-cpu 800M # Memory per allocated CPU, strongly advised to customize, default is 500M
#SBATCH --time 1-01:00:00 ## Must be specified, the default for this partition is 7 days 1 hour max walltime (7-01:00:00)
#SBATCH --mail-user gsmithvi@nmsu.edu
#SBATCH --mail-type BEGIN ## will get an email when job starts
#SBATCH --mail-type END ## will get an email when job ends
#SBATCH --mail-type FAIL ## will get email when job fails
#SBATCH --get-user-env ## wpass on environmental settings

module load stacks

# Use input files from process_radtags (demultiplexed and quality control processed)
src=/scratch/gsmithvi/cleaned/process_radtags/paired_end
out_path=/scratch/gsmithvi/cleaned/clone_filter

# Save the standard output and error to a file
log_file=$out_path/clone_filter.oe

# Get the first file in each pair
files=`for i in $src; do
        find $i*/ -type f -iname "*[[:upper:]].1.fq.gz";
done`

# Specify either a path (not working) or a set of paired end files, but not both
# Run the for loop using array indices to pull out the first and second files in each pair per sample
#for i in $files; do
#	# echo ${i%%.*}.2.fq.gz; # checking
#	# Extract the paired and non-paired file names
#	clone_filter -1 ${i%%.*}.1.fq.gz -2 ${i%%.*}.2.fq.gz -o $out_path -i gzfastq -D;
#done &> $log_file

# 02 August 2020
# Run clone_filter for the sample lib2_ELGE_NMSU-208 that fails when run with all samples
log_file2=$out_path/clone_filter2.oe

clone_filter -1 $src/PE_lib2_NAT_ELGE_NMSU-208_CCGTGAGA.1.fq.gz -2 $src/PE_lib2_NAT_ELGE_NMSU-208_CCGTGAGA.2.fq.gz -o $out_path -i gzfastq -D &> $log_file2
