#!/bin/bash
## G.Smith-Vidaurre
## 25 June 2020

## Purpose: Demultiplex paired-end libraries in Stacks on the Discovery supercomputer. The script can be executed by entering "sbatch path2script/nameofscript" since the paths to files are absolute.

#SBATCH --job-name process_radtagsPE
#SBATCH --partition normal ## default
#SBATCH --nodes 1 ## default
#SBATCH --ntasks 1 ## default
#SBATCH --cpus-per-task 16 ## number of threads, default is 1, changes ntasks, I still find that confusing
#SBATCH --time 1-01:00:00 ## Must be specified, the default for this partition is 7 days 1 hour max walltime (7-01:00:00)
#SBATCH --mail-user gsmithvi@nmsu.edu
#SBATCH --mail-type BEGIN ## will get an email when job starts
#SBATCH --mail-type END ## will get an email when job ends
#SBATCH --mail-type FAIL ## will get email when job fails
#SBATCH --get-user-env ## wpass on environmental settings

module load stacks

src=/scratch/gsmithvi/raw/paired_end_2019
bc_path=/scratch/gsmithvi/info/barcodes
out_path=/scratch/gsmithvi/cleaned/process_radtags/paired_end

# Run process_radtags on library 1
process_radtags -P \
        -o $out_path -b $bc_path/PE_barcodes_library1.txt \
        -e sbfI -r -c -q -D --inline_null -1 $src/lib1/SOMM475_R1_TTAACT.fastq.gz -2 $src/lib1/SOMM475_R3_TTAACT.fastq.gz --bestrad 

# Run process_radtags on library 2
process_radtags -P \
        -o $out_path -b $bc_path/PE_barcodes_library2.txt \
        -e sbfI -r -c -q -D --inline_null -1 $src/lib2/SOMM475_R1_TACTAT.fastq.gz -2 $src/lib2/SOMM475_R3_TACTAT.fastq.gz --bestrad 

