#!/bin/bash
# G.Smith-Vidaurre
# 15 May 2020

# Purpose: Demultiplex paired-end libraries in Stacks

src=/media/owner/MYIOPSITTA/R/Origins_Selection/raw/paired_end_2019
out_path=/media/owner/MYIOPSITTA/R/Origins_Selection

# Run process_radtags on library 1
/usr/local/bin/process_radtags -P \
        -o $out_path/samples/paired_end_2019 -b $out_path/barcodes/PE_barcodes_library1.txt \
        -e sbfI -r -c -q -D --inline_null -1 $src/lib1/SOMM475_R1_TTAACT.fastq.gz -2 $src/lib1/SOMM475_R3_TTAACT.fastq.gz --bestrad 

# Run process_radtags on library 2
/usr/local/bin/process_radtags -P \
        -o $out_path/samples/paired_end_2019 -b $out_path/barcodes/PE_barcodes_library2.txt \
        -e sbfI -r -c -q -D --inline_null -1 $src/lib2/SOMM475_R1_TACTAT.fastq.gz -2 $src/lib2/SOMM475_R3_TACTAT.fastq.gz --bestrad 

