#!/bin/bash
## G.Smith-Vidaurre
## 22 September 2020

## Purpose: Run Structure over K1 to K26 with the merged pre-processed neutral SNPs. Each K will be run 10 times.

#SBATCH --job-name Structure
#SBATCH --partition normal ## default
#SBATCH --nodes 1 ## default
#SBATCH --ntasks 1 ## default
#SBATCH --cpus-per-task 32 ## number of threads, default is 1, changes ntasks, I still find that confusing
#SBATCH --mem-per-cpu 3000M
#SBATCH --time 7-00:00:00 ## Must be specified, the default for this partition is 7 days 1 hour max walltime (7-01:00:00)
#SBATCH --mail-user gsmithvi@nmsu.edu
#SBATCH --mail-type BEGIN ## will get an email when job starts
#SBATCH --mail-type END ## will get an email when job ends
#SBATCH --mail-type FAIL ## will get email when job fails
#SBATCH --get-user-env ## pass on environmental settings

module load structure

src=/scratch/gsmithvi/Structure

# Iterate over K, perform 10 iterations per K value
for K in `seq 1 26`;
	do
	out_path=$src/K$K;
	
	for i in `seq 1 10`;
		do
		file=merged_neutralSNPs_K$K_rep$i
		structure -K $K -o $out_path/$file
	done
done
