#!/bin/bash
## G.Smith-Vidaurre
## 03 October 2020
## Updated 08 October 2020

## Purpose: Run fastsimcoal2 over demographic models in delimitR examples to get simulated data for ABC modelling. 

#SBATCH --job-name ABC_sims_test
#SBATCH --partition normal ## default
#SBATCH --nodes 1 ## default
#SBATCH --ntasks 1 ## default
#SBATCH --cpus-per-task 32 ## number of threads, default is 1, changes ntasks, I still find that confusing
#SBATCH --mem-per-cpu 2000M # default is 500M
#SBATCH --time 7-00:00:00 ## Must be specified, the default for this partition is 7 days 1 hour max walltime (7-01:00:00)
#SBATCH --mail-user gsmithvi@nmsu.edu
#SBATCH --mail-type BEGIN ## will get an email when job starts
#SBATCH --mail-type END ## will get an email when job ends
#SBATCH --mail-type FAIL ## will get email when job fails
#SBATCH --get-user-env ## pass on environmental settings


module load fastsimcoal2

# Need to iterate over models 

#cd /scratch/gsmithvi/ABC/example # Change working directory for the run below
#path=/scratch/gsmithvi/ABC/example
#prefix=tutorial_guidetree1
#logfile=$path/example_fcs26_log.oe

#for i in `seq 1 4`;
 #       do
 #       fsc26 -t $path/$prefix"_$i".tpl -e $path/$prefix"_$i".est -n 1 -E 10 --msfs --multiSFS -x &> $logfile;
#done


# BARC

cd /scratch/gsmithvi/ABC/ABC_BARC # Change working directory for the run below
path=/scratch/gsmithvi/ABC/ABC_BARC
prefix=BARC_model
logfile=$path/BARC_fsc26_log.oe

# -E is the number of draws from parameter priors, -n is the number of simulations to perform per set of parameters drawn. Megan Smith suggests a minimum of 10k draws, and set n to 1, here I will set n to 1 as well
# --msfs: computes the SFS for the minor allele in each population sample, for all pairs of samples (join SFS), and for all populations pooled (global SFS), SNPs only
# -q: silences messages to console
# --multiSFS: generate or use multidimensional SFS
# -x: do not generate Arlequin output files
# -0: do no consider number of monomorphic sites
for i in `seq 1 6`;
        do
        fsc26 -t $path/$prefix"_$i".tpl -e $path/$prefix"_$i".est -q -n 1 -E 10000 --msfs --multiSFS -x &> $logfile;
done

