#!/bin/bash
# G. Smith-Vidaurre
# 05 October 2020

# Purpose: Run CLUMPP on local machine to combine Structure replicates per K and order clusters. CLUMPP input files and paramfiles generated using pophelper package in "Structure_graphics.Rmd".

src=/home/owner/Desktop/Software/CLUMPP_Linux32.1.1.2
path=/media/owner/MYIOPSITTA/R/Origins_Selection/Structure

for i in `seq 2 26`; 
	do
	tmp_path=$path/pop_K"$i";
	# echo $tmp_path;
	$src/CLUMPP $tmp_path/paramfile -p $tmp_path/pop_K"$i"-combined.txt;
done



