#!/bin/bash
# G.Smith-Vidaurre
# 02 June 2020

# Purpose: Use kmer abundance patterns to evaluate error rates and repeats in the single-end libraries

src=/media/owner/MYIOPSITTA/R/Origins_Selection/samples/single_end_2015
out_path=/media/owner/MYIOPSITTA/R/Origins_Selection/kmer_output/single_end_2015

files=`for i in $src; do
        find $i*/ -type f -iname "*fq.gz";
done`

for i in $files; do
	# echo $i; # checking

	# Run kmer_filter on demultiplexed reads, with filtering based on both rare (sequencing or PCR error) and abundant (repetitive loci) k-mers, default k-mer size of 15, no advanced filtering options and no read depth normalization
	/usr/local/bin/kmer_filter -f $i -o $out_path -i gzfastq -D --k_len 15 --rare --abundant;

done
