#!/bin/bash
## G.Smith-Vidaurre
## 23 June 2020

## Purpose: Demultiplex single-end libraries in Stacks on the Discovery supercomputer. The script can be executed by entering "sbatch path2script/nameofscript" since the paths to files are absolute.

#SBATCH --job-name process_radtagsLib1
#SBATCH --partition normal ## default
#SBATCH --nodes 1 ## default
#SBATCH --ntasks 1 ## default
#SBATCH --cpus-per-task 16 ## number of threads, default is 1, changes ntasks, I still find that confusing
#SBATCH --time 1-01:00:00 ## Must be specified, the default for this partition is 7 days 1 hour max walltime (7-01:00:00)
#SBATCH --mail-user gsmithvi@nmsu.edu
#SBATCH --mail-type BEGIN ## will get an email when job starts
#SBATCH --mail-type END ## will get an email when job ends
#SBATCH --mail-type FAIL ## will get email when job fails
#SBATCH --get-user-env ## wpass on environmental settings

module load stacks

src=/scratch/gsmithvi/raw/single_end_2015
bc_path=/scratch/gsmithvi/info/barcodes
out_path=/scratch/gsmithvi/cleaned/process_radtags/single_end

## Run process_radtags on library 1
process_radtags -p $src/lib1 \
        -o $out_path -b $bc_path/SE_barcodes_library1.txt \
        -e sbfI -r -c -q -D --inline_null

## Run process_radtags on library 2
process_radtags -p $src/lib2 \
        -o $out_path -b $bc_path/SE_barcodes_library2.txt \
        -e sbfI -r -c -q -D --inline_null

